CREATE DATABASE IF NOT EXISTS SIGNPROJECT;
DROP TABLE IF EXISTS  `SIGNPROJECT`.`USERS`;
CREATE TABLE `SIGNPROJECT`.`USERS`(
   `id` VARCHAR(20) NOT NULL,
    `password` TEXT NOT NULL
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;